autentikacija/urls.py
from django.urls import path
from . import views

app_name = 'autentikacija'

urlpatterns = [
    path('', views.registracija, name = 'registracija'),
    path('prijava/', views.prijava, name = 'prijava'),
    path('odjava/', views.odjava, name = 'odjava'),
]

toDoApp/urls.py
from django.urls import path
from . import views

app_name = 'toDoApp'

urlpatterns = [
    path('', views.toDo, name = 'toDo'),
    path('novi', views.noviTodo, name = 'noviTodo'),
    path('zavrsi<int:todo_id>/', views.zavrsi, name = 'zavrsi'),
    path('uredi<int:todo_id>/', views.uredi, name = 'uredi'),
    path('izbrisi<int:todo_id>/', views.izbrisi, name = 'izbrisi'),
    path('zavrseno/', views.zavrseno, name = 'zavrseno'),
]

toDoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autentikacija.urls')),
    path('todo/', include('toDoApp.urls')),
]

autentikacija/models.py
from django.db import models

# Create your models here.

toDoApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class todo(models.Model):
    naslov = models.CharField(max_length = 100)
    opis = models.TextField(blank = True)
    važno = models.BooleanField(default = False)
    datumZavrsetka = models.DateTimeField(null = True, blank = True)
    userID = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return self.naslov

toDoApp/forms.py
from django.forms import ModelForm 
from .models import todo

class toDoForm(ModelForm):
    class Meta:
        model = todo
        fields = ['naslov', 'opis', 'važno']

autentikacija/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, authenticate, logout
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.decorators import login_required

# Create your views here. 

def registracija(request):
    if request.method == 'GET':
        return render(request, 'autentikacija/registracija.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                validate_password(request.POST['password1'])
            except ValidationError as greska:
                return render(request, 'autentikacija/registracija.html', {'form': UserCreationForm(), 'greska': greska})
            try:
                user = User.objects.create_user(request.POST['username'], password = request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('toDoApp:toDo')
            except IntegrityError:
                return render(request, 'autentikacija/registracija.html', {'form': UserCreationForm(), 'greska': 'Korisničko ime je već zauzeto. Pokušajte ponovo.'})
        else:
            return render(request, 'autentikacija/registracija.html', {'form': UserCreationForm(), 'greska': 'Lozinke se ne podudaraju. Pokušajte ponovo.'})


def prijava(request):
    if request.method == 'GET':
        return render(request, 'autentikacija/prijava.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(request, username = request.POST['username'], password = request.POST['password'])
        if user is None:
            return render(request, 'autentikacija/prijava.html', {'form': AuthenticationForm(), 'greska': 'Korisničko ime i lozinka se ne podudaraju. Pokušajte ponovo.'})
        else:
            login(request, user)
            return redirect('toDoApp:toDo')

@login_required
def odjava(request):
    if request.method == 'POST':
        logout(request)
        return redirect('autentikacija:prijava')

toDoApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import toDoForm
from .models import todo
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def toDo(request):
    todos = todo.objects.filter(userID = request.user, datumZavrsetka__isnull = True).order_by('-važno')
    return render(request, 'toDoApp/todo.html', {'todos': todos})

@login_required
def noviTodo(request):
    if request.method == 'GET':
        return render(request, 'toDoApp/noviTodo.html', {'form': toDoForm()})
    else:
        form = toDoForm(request.POST)
        noviTodo = form.save(commit = False)
        noviTodo.userID = request.user
        noviTodo.save()
        return redirect('toDoApp:toDo')

@login_required
def zavrsi(request, todo_id):
    Todo = get_object_or_404(todo, pk = todo_id, userID = request.user)
    Todo.datumZavrsetka = timezone.now()
    Todo.save()
    return redirect('toDoApp:toDo')

@login_required
def uredi(request, todo_id):
    Todo = get_object_or_404(todo, pk = todo_id, userID = request.user)
    if request.method == 'GET':
        form = toDoForm(instance = Todo)
        return render(request, 'toDoApp/uredi.html', {'form': form})
    else:
        form = toDoForm(request.POST, instance = Todo)
        form.save()
        return redirect('toDoApp:toDo')

@login_required
def izbrisi(request, todo_id):
    Todo = get_object_or_404(todo, pk = todo_id, userID = request.user)
    Todo.delete()
    return redirect('toDoApp:toDo')

@login_required
def zavrseno(request):
    todos = todo.objects.filter(userID = request.user, datumZavrsetka__isnull = False).order_by('-datumZavrsetka')
    return render(request, 'toDoApp/zavrseno.html', {'todos': todos})

autentikacija/templates/autentikacija/base.html
{% load static %}
<!doctype html>
<html lang="hr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'autentikacija/style.css' %}">

    <title>To Do List</title>
  </head>
  <body>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm justify-content-center align-items-center lijeva">
              <div class="jumbotron">
                <h1>Dobrodošli na <span class="naziv">To Do List</span></h1><br><br>
                <h2>Aplikacija koja vam olakšava upravljanje svakodnevnim obavezama i zadacima</h2><br><br>
                <div class="row justify-content-center gumbi">
                  <a href="{% url 'autentikacija:registracija' %}" class="col-sm-3 registriraj">Registrirajte se</a>
                  <a href="{% url 'autentikacija:prijava' %}" class="col-sm-3 prijavi">Prijavite se</a>
                </div>
              </div>
            </div>
            <div class="col-sm desna justify-content-center align-items-center">
                {% block sadrzaj %}{% endblock %}
            </div>
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
  </body>
</html>

autentikacija/templates/autentikacija/prijava.html
{% extends 'autentikacija/base.html' %}
{% load static %}
{% block sadrzaj %}

<br>
<img src="{% static 'autentikacija/prijava.png' %}" width="150px" height="150px" class="slika">
<h1 class="naslov">Prijava</h1><br>
<div class="registracija">
    <form method="POST">
        {% if greska %}
        <div class="alert alert-danger" role="alert">
            {{ greska }}
        </div>
        {% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Prijavite se</button>
    </form>
</div>

{% endblock %}

autentikacija/templates/autentikacija/registracija.html
{% extends 'autentikacija/base.html' %}
{% load static %}
{% block sadrzaj %}

<br>
<img src="{% static 'autentikacija/registracija.png' %}" width="150px" height="150px" class="slika">
<h1 class="naslov">Registracija</h1><br>
<div class="registracija">
    <form method="POST">
        {% if greska %}
        <div class="alert alert-danger" role="alert">
            {{ greska }}
        </div>
        {% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Registrirajte se</button>
    </form>
</div>

{% endblock %}

toDoApp/templates/toDoApp/base.html
{% load static %}
<!doctype html>
<html lang="hr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'toDoApp/style.css' %}">

    <title>To Do List</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'toDoApp:toDo' %}">
                <img src="{% static 'toDoApp/logo.png' %}" width="50px" height="50px">
                To Do
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'toDoApp:toDo' %}">Popis zadataka</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'toDoApp:noviTodo' %}" style="margin-left: 20px;margin-right: 10px">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
                                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
                            </svg>
                            Stvori novi zadatak
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'toDoApp:zavrseno' %}">Zavrseni zadaci</a>
                    </li>
                </ul>
                    <form class="d-flex" action="{% url 'autentikacija:odjava' %}" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-dark" type="submit">Prijavljeni ste kao {{ user.username }}
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"/>
                            <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
                        </svg>
                        </button>
                    </form>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        {% block sadrzaj %}{% endblock %}
    </div>

    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
  </body>
</html>

toDoApp/templates/toDoApp/noviTodo.html
{% extends 'toDoApp/base.html' %}
{% block sadrzaj %}

<h1>Dodaj novi zadatak</h1>
<div style="text-align: center">
<div class="jumbotron">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark spremi">Dodaj</button>
    </form>
</div>
</div>

{% endblock %}

toDoApp/templates/toDoApp/todo.html
{% extends 'toDoApp/base.html' %}
{% load static %}
{% block sadrzaj %}

<h1>Popis zadataka</h1>
{% if not todos %}
<div class="done">
    <h4>Trenutno nemate niti jednu obavezu.</h4>
    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-emoji-smile" viewBox="0 0 16 16">
    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
    <path d="M4.285 9.567a.5.5 0 0 1 .683.183A3.498 3.498 0 0 0 8 11.5a3.498 3.498 0 0 0 3.032-1.75.5.5 0 1 1 .866.5A4.498 4.498 0 0 1 8 12.5a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .183-.683zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z"/>
    </svg>
    <img src="{% static 'toDoApp/done.jpg' %}">
</div>
{% endif %}
<div class="row">
{% for todo in todos %} <!-- for petlja -->
<div class="col-sm-3">
<div class="card border-primary mb-3 {% if todo.važno %}border-danger{% endif %}" style="max-width: 18rem;">
  <div class="card-header" style="text-align: center; font-weight: bold">
    {{ todo.naslov }} <!-- naslov todo objekta -->
    {% if todo.važno %}
    <img src="{% static 'toDoApp/important.png' %}" width="30px" height="30px" style="float: left">
    {% endif %}
  </div>
  <div class="card-body text-secondary">
    <p class="card-text" style="color: black;{% if not todo.opis %}visibility: hidden{% endif %}">
        {% if not todo.opis %}Bez opisa{% endif %}
        {{ todo.opis }} <!-- opis todo objekta -->
    </p>
    <hr>
    <a href="{% url 'toDoApp:zavrsi' todo.id %}" class="akcije" id="zavrsi">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-lg" viewBox="0 0 16 16">
            <path d="M13.485 1.431a1.473 1.473 0 0 1 2.104 2.062l-7.84 9.801a1.473 1.473 0 0 1-2.12.04L.431 8.138a1.473 1.473 0 0 1 2.084-2.083l4.111 4.112 6.82-8.69a.486.486 0 0 1 .04-.045z"/>
        </svg>
    </a>
    <a href="{% url 'toDoApp:uredi' todo.id %}" class="akcije" id="uredi">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
            <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
        </svg>
    </a>
    <a href="{% url 'toDoApp:izbrisi' todo.id %}" class="akcije" id="brisi">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
            <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
        </svg>
    </a>
  </div>
</div>
</div>
{% endfor %}
</div>

{% endblock %}

toDoApp/templates/toDoApp/uredi.html
{% extends 'toDoApp/base.html' %}
{% block sadrzaj %}

<h1>Uredi</h1>
<div style="text-align: center">
<div class="jumbotron">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark spremi">Uredi</button>
    </form>
</div>
</div>

{% endblock %}

toDoApp/templates/toDoApp/zavrseno.html
{% extends 'toDoApp/base.html' %}
{% load static %}
{% block sadrzaj %}

<h1>Završeni zadaci</h1>
<div class="row">
{% for todo in todos %}
<div class="col-sm-3">
<div class="card border-primary mb-3 {% if todo.važno %}border-danger{% endif %}" style="max-width: 18rem; height: 220px">
  <div class="card-header" style="text-align: center; font-weight: bold">
    {{ todo.naslov }}
    {% if todo.važno %}
    <img src="{% static 'toDoApp/important.png' %}" width="30px" height="30px" style="float: left">
    {% endif %}
  </div>
  <div class="card-body text-secondary">
    <h5 class="card-title">Završeno na dan {{ todo.datumZavrsetka }}</h5>
    <p class="card-text" style="color: black;{% if not todo.opis %}visibility: hidden{% endif %}">
        {% if not todo.opis %}Bez opisa{% endif %}
        {{ todo.opis }}
    </p>
    <hr>
    <a href="{% url 'toDoApp:izbrisi' todo.id %}" class="akcije" id="brisi">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
            <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
        </svg>
    </a>
  </div>
</div>
</div>
{% endfor %}
</div>

{% endblock %}